name: CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: yarn
      - run: yarn build

      - name: Copy folder content recursively to remote
        uses: undg/github-action-scp@release
        with:
          local: _site
          remote: ${{ secrets.SSH_PATH }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PWD }}
