name: CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: yarn
      - run: yarn build

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3


      - name: rsync stuff to the thing
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASS: ${{ secrets.SSH_PWD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_PATH: ${{ secrets.SSH_PATH }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
          sshpass -p "$SSH_PASS" rsync -e "ssh -p $SSH_PORT" -avz --progress _site/ $SSH_USER@$SSH_HOST:$SSH_PATH

