name: CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v4
      # - run: yarn
      # - run: yarn build

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3


      - name: rsync stuff to the thing
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASS: ${{ secrets.SSH_PWD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_PATH: ${{ secrets.SSH_PATH }}

        run: |
          echo "SSH_PATH: $SSH_PATH"
          echo "SSH_PASS: $SSH_PASS"
          echo "SSH_HOST: $SSH_HOST"
          echo "SSH_USER: $SSH_USER"
          echo "SSH_PORT: $SSH_PORT"
          sshpass -p "$SSH_PASS" rsync -e "ssh -p $SSH_PORT" -avz --progress _site/ $SSH_USER@$SSH_HOST:$SSH_PATH

      # - name: copy file via ssh password
      #   uses: appleboy/scp-action@v0.1.7
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     password: ${{ secrets.SSH_PWD }}
      #     port: ${{ secrets.SSH_PORT }}
      #     source: "_site"
      #     target: ${{ secrets.SSH_PATH }}

      # - name: Copy folder content recursively to remote
      #   # @TODO (undg) 2024-06-17: use fork for now
      #   # uses: undg/github-action-scp@master
      #   uses: garygrossgarten/github-action-scp@release
      #   with:
      #     local: _site
      #     remote: ${{ secrets.SSH_PATH }}
      #     host: ${{ secrets.SSH_HOST }}
      #     port: ${{ secrets.SSH_PORT }}
      #     username: ${{ secrets.SSH_USER }}
      #     password: ${{ secrets.SSH_PWD }}
